" use gui tabs
set guioptions+=e

" kill the menubar
set guioptions-=T

" kill the scrollbars
set guioptions-=r
set guioptions-=L

" use a big, pretty font
set guifont=Consolas:h11

" initial window size
set lines=31 columns=100

runtime! custom_config/*.gvim

" vim:ft=vim:
